# Generated by Django 3.1.2 on 2021-11-19 15:05
import logging
import sys

from django.db import migrations
from recommenders import RM_gettogether
from backend import models


def reset_recommendations(apps, schema_editor):
    userrecs = models.SiddataUserRecommender.objects.filter(recommender__classname="RM_gettogether",
                                                            enabled=True, )
    recommender = RM_gettogether.RM_gettogether()
    print("Userreces: {}".format(len(userrecs)))
    i = 1
    TEST = False
    for sur in userrecs:
        if sur.enabled == False:
            continue
        i += 1
        if i == 20 and TEST:
            sys.exit()
        try:

            form_goal = models.Goal.objects.get(
                title=recommender.get_name(),
                userrecommender=sur,
            )
            recommendations = models.Activity.objects.filter(goal=form_goal)
            if len(recommendations) > 0:
                for a in recommendations:
                    if a.person and a.type == "person":
                        a.person.delete()
                    a.delete()

            form_goal.delete()
        except:
            logging.info("No form goal")

        try:
            personal_matches_goal = models.Goal.objects.get(
                title=RM_gettogether.MY_CONTACTS_TITLE,
                userrecommender=sur,
            )

            recommendations = models.Activity.objects.filter(goal=personal_matches_goal)
            if len(recommendations) > 0:
                for a in recommendations:
                    if a.person and a.type == "person":
                        a.person.delete()
                    a.delete()
                recommendations.delete()

            personal_matches_goal.delete()
        except:
            logging.info("No personal matches goal")

        try:
            available_contacts_goal = models.Goal.objects.get(
                title=RM_gettogether.ALL_CONTACTS_TITLE,
                userrecommender=sur,
            )

            recommendations = models.Activity.objects.filter(goal=available_contacts_goal)
            if len(recommendations) > 0:
                for a in recommendations:
                    if a.person and a.type == "person":
                        a.person.delete()
                    a.delete()
                recommendations.delete()
            available_contacts_goal.delete()
        except:
            logging.info("No all contacts goal")

        if sur.enabled == True:
            # set back to initial state
            recommender.initialize(sur.user)



class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0002_recommender_active'),
    ]

    operations = [
        migrations.RunPython(reset_recommendations),
    ]
