# Generated by Django 3.1.2 on 2021-12-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_gettogether_data_reset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(default='new', max_length=64),
        ),
    ]
