# Generated by Django 3.2.9 on 2022-02-07 11:07

from django.db import migrations
import languages.fields


activity_changeset = [
    {
        "title": "Neue Version 3.0 - neuer Start",
        "description": "Der Siddata Studienassistent in der Version 3.0 wurde grundlegend erneuert. "
                       "Daher wurden alle Einstellungen und Daten alter Versionen archiviert. Die Rohdaten können "
                       "bei Bedarf angefragt und in maschinenlesbarer Form erhalten werden.<br><br>"
                       "Viel Spaß beim Erkunden der neuen Funktionen!",
        "title_new": "Neue Version, neuer Start!",
        "description_new": "Siddata wurde grundlegend erneuert. Daher wurden alle Einstellungen und Daten alter "
                           "Versionen archiviert. Du kannst deine Rohdaten bei Bedarf bei uns anfragen und in "
                           "maschinenlesbarer Form erhalten. <br><br>Viel Spaß beim Erkunden der neuen Funktionen!"
    },
    {
        "description": "Schaue Dir die Partneruniversitäten an und wähle zunächst 2-3 Angebote aus, die für Dich in Frage kommen würden.",
        "description_new": "Schaue dir die Partneruniversitäten an und wähle zunächst 2-3 Angebote aus, die für Dich in Frage kommen würden."
    },
    {
        "description": "Vergleiche die Kursangebote der Gastuniversitäten und suche Dir nun ein Favorit aus.",
        "description_new": "Vergleiche die Kursangebote der Gastuniversitäten und suche dir nun ein Favorit aus."
    },
    {
        "description": "Erstelle eine Liste der benötigten Unterlagen in Absprache mit dem Erasmus-Koordinator "
                       "deiner Fakultät. (Du kannst dich an dieser Liste orientieren, beachte aber dass jede "
                       "Fakultät unterschiedliche Kriterien hat)",
        "description_new": "Erstelle eine Liste der benötigten Unterlagen in Absprache mit der Erasmus-Koordination "
                           "deiner Fakultät. (Du kannst dich an dieser Liste orientieren, beachte aber dass jede "
                           "Fakultät unterschiedliche Kriterien hat)"
    },
    {
        "description": "Lass Dir die Sprachkenntnisse nachweisen, bzw. besuche einen Kurs am Sprachenzentrum.",
        "description_new": "Lass dir die Sprachkenntnisse nachweisen, bzw. besuche einen Kurs am Sprachenzentrum."
    },
    {
        "description": "Suche Dir passende Kurse an der Gastuniversität. Fülle das Online Learning Agreement "
                       "aus und leite es an deinen Erasmuskoordinator. Bei Mobilität im WiSe: Abgabe bis 30. ",
        "description_new": "Suche dir passende Kurse an der Gastuniversität. Fülle das Online Learning Agreement "
                           "aus und leite es an deine Erasmus-Koordination. Bei Mobilität im WiSe: Abgabe bis 30. "
                           "April. Bei Mobilität im SoSe: Abgabe bis 30. September."
    },
    {
        "description": "Gleich nach der Zusage: Informiere Dich, ob Dir AuslandsBAföG zusteht.",
        "description_new": "Gleich nach der Zusage: Informiere dich, ob dir AuslandsBAföG zusteht."
    },
    {
        "description": "Finde heraus, ob du ein Visum oder Aufenthaltsberechtigung für das Gastland brauchst.",
        "description_new": "Finde heraus, ob du ein Visum oder eine Aufenthaltsberechtigung für das Gastland brauchst."
    },
    {
        "description": "Manche Gastuniversitäten bieten kostenlose Sprachkurse bei Ankunft an. Diese sind "
                       "wertvoll, um direkt Kontakte zu anderen Erasmus-Teilnehmenden zu knüpfen. Dafür muss "
                       "allerdings von zu Hause aus ein Einstufungstest durchgeführt werden. Suche solch "
                       "einen Test auf der Webseite der Gastuniversität.",
        "description_new": "Manche Gastuniversitäten bieten kostenlose Sprachkurse bei Ankunft an. Diese sind "
                           "wertvoll, um direkt Kontakte zu anderen Erasmus-Teilnehmenden zu knüpfen. Dafür muss "
                           "allerdings von zu Hause aus ein Einstufungstest durchgeführt werden. Suche solch "
                           "einen Test auf der Webseite der Gastuniversität.",
    },
    {
        "description": "Suche Dir eine passende Unterkunft. Damit kann Dir die Gastuniversität ggf. "
                       "weiterhelfen.",
        "description_new": "Suche dir eine passende Unterkunft. Damit kann dir die Gastuniversität ggf. "
                           "weiterhelfen."
    },
    {
        "description": "Buche einen Flug und freu Dich auf die Reise. Wir wünschen Dir ein unvergessliches "
                       "Abenteuer.",
        "description_new": "Buche einen Flug und freu Dich auf die Reise. Wir wünschen dir ein unvergessliches "
                           "Abenteuer."
    },
    {
        "description": "Vergleiche die Kursangebote der Gastuniversitäten und suche Dir nun einen Favoriten aus.",
        "description_new": "Vergleiche die Kursangebote der Gastuniversitäten und suche dir nun einen Favoriten aus."
    },
    {
        "description": "Nimm Kontakt zum Erasmus Student Network (ESN) auf, dort lernst du andere Erasmusbegeisterte kennen und erfährst aus erster Hand wie ein Auslandsaufenthalt zu organisieren ist.",
        "description_new": "Nimm Kontakt zum Erasmus Student Network (ESN) auf, dort lernst du andere Erasmusbegeisterte kennen und erfährst aus erster Hand, wie ein Auslandsaufenthalt zu organisieren ist."
    },
    {
        "description": "Erstelle eine Liste der benötigten Unterlagen in Absprache mit dem Erasmus-Koordinator deiner Fakultät.",
        "description_new": "Erstelle eine Liste der benötigten Unterlagen in Absprache mit der Erasmus-Koordination deiner Fakultät."
    },
    {
        "description": "Lass Dir die Sprachkenntnisse nachweisen, bzw. besuche einen Kurs am Sprachenzentrum.",
        "description_new": "Lass dir die Sprachkenntnisse nachweisen, bzw. besuche einen Kurs am Sprachenzentrum."
    },
    {
        "description": "Suche Dir passende Kurse an der Gastuniversität aus. Fülle das Online Learning Agreement aus und leite es an dne/n Fachbereichskoordinator:in mit der Bitte um Unterzeichnung. Dieses Dokument ist für die Anrechnung der Ausland bestandenen Module notwendig.",
        "description_new": "Suche dir passende Kurse an der Gastuniversität aus. Fülle das Online Learning Agreement aus und leite es an dne/n Fachbereichs-Koordination mit der Bitte um Unterzeichnung. Dieses Dokument ist für die Anrechnung der im Ausland bestandenen Module notwendig."
    },
    {
        "description": "Informiere Dich mindestens sechs Monate im Voraus, ob Dir Auslands-BAföG zusteht.",
        "description_new": "Informiere Dich mindestens sechs Monate im Voraus, ob dir Auslands-BAföG zusteht."
    },
    {
        "description": "Finde heraus, ob du ein Visum oder Aufenthaltsberechtigung für das Gastland benötigst.",
        "description_new": "Finde heraus, ob du ein Visum oder eine Aufenthaltsberechtigung für das Gastland benötigst."
    },
    {
        "description": "Manche Gastuniversitäten bieten kostenlose Sprachkurse bei Ankunft an. Diese sind wertvoll, um "
                       "direkt Kontakte zu anderen Erasmus-Teilnehmern zu knüpfen. Dafür muss allerdings von zu Hause "
                       "aus ein Einstufungstest durchgeführt werden. Suche solch einen Test auf der Webseite der "
                       "Gastuniversität.",
        "description_new": "Manche Gastuniversitäten bieten kostenlose Sprachkurse bei Ankunft an. Diese sind wertvoll, um "
                           "direkt Kontakte zu anderen Erasmus-Teilnehmenden zu knüpfen. Dafür muss allerdings von zu Hause "
                           "aus ein Einstufungstest durchgeführt werden. Suche solch einen Test auf der Webseite der "
                           "Gastuniversität."
    },
    {
        "description": "Suche Dir eine passende Unterkunft. Damit kann Dir die Gastuniversität ggf. weiterhelfen.",
        "description_new": "Suche dir eine passende Unterkunft. Damit kann dir die Gastuniversität ggf. weiterhelfen."
    },
    {
        "description": "Buche einen Flug und freu Dich auf die Reise. Wir wünschen Dir ein unvergessliches Abenteuer.",
        "description_new": "Buche einen Flug und freu Dich auf die Reise. Wir wünschen dir ein unvergessliches Abenteuer."
    },
    {
        "description": "Vergleiche die Kursangebote der Gastuniversitäten und suche Dir nun einen Favoriten aus.",
        "description_new": "Vergleiche die Kursangebote der Gastuniversitäten und suche dir nun einen Favoriten aus."
    },
    {
        "description": "Lies einige Erfahrungsberichte von Studierenden, die bereits im Ausland waren. deine Uni arbeitet "
                       "noch an einer Sammlung von Erfahrungsberichten. Auf der Internetseite deines Fachbereichs findest "
                       "du Erfahrungsberichte von anderen Studierenden. Eine gute Übersicht findest du auf der "
                       "Internetseite unseres Verbundpartners, der Leibniz Universität Hannover.",
        "description_new": "Lies einige Erfahrungsberichte von Studierenden, die bereits im Ausland waren. Deine Uni arbeitet "
                           "noch an einer Sammlung von Erfahrungsberichten. Auf der Internetseite deines Fachbereichs findest "
                           "du Erfahrungsberichte von anderen Studierenden. Eine gute Übersicht findest du auf der "
                           "Internetseite unseres Verbundpartners, der Leibniz Universität Hannover."
    },
    {
        "description": "Nimm Kontakt zum Erasmus Student Network (ESN) auf, dort lernst du andere Erasmusbegeisterte "
                       "kennen und erfährst aus erster Hand wie ein Auslandsaufenthalt zu organisieren ist. ",
        "description_new": "Nimm Kontakt zum Erasmus Student Network (ESN) auf, dort lernst du andere Erasmusbegeisterte "
                           "kennen und erfährst aus erster Hand, wie ein Auslandsaufenthalt zu organisieren ist. "
    },
    {
        "description": "Erstelle eine Liste der benötigten Unterlagen in Absprache mit dem Erasmus-Koordinator deiner "
                       "Fakultät.",
        "description_new": "Erstelle eine Liste der benötigten Unterlagen in Absprache mit der Erasmus-Koordination deiner "
                           "Fakultät."
    },
    {
        "description": "Suche dir passende Kurse an der Gastuniversität. Fülle das Online Learning Agreement aus und "
                       "leite es an deine/n Fachbereichskoordinator:in mit der Bitte um Unterzeichnung. Dieses Dokument "
                       "ist für die Anrechnung der Ausland bestandenen Module notwendig.",
        "description_new": "Suche dir passende Kurse an der Gastuniversität. Fülle das Online Learning Agreement aus und "
                           "leite es an deine/n Fachbereichs-Koordination mit der Bitte um Unterzeichnung. Dieses Dokument "
                           "ist für die Anrechnung der im Ausland bestandenen Module notwendig."
    },
    {
        "description": "Leite das vorläufige Learning Agreement an die Erasmuskoordination deines International Office "
                       "weiter, sobald dein vorläufiges Learning Agreement mit deiner/m Fachbereichskoordinator:in "
                       "abgestimmt ist. Änderungen kannst du noch zu Beginn deines Auslandsstudiums mit dem Learning "
                       "Agreement - During the Mobility vornehmen.",
        "description_new": "Leite das vorläufige Learning Agreement an die Erasmus-Koordination deines International Office "
                           "weiter, sobald dein vorläufiges Learning Agreement mit deiner/m Fachbereichs-Koordination "
                           "abgestimmt ist. Änderungen kannst du noch zu Beginn deines Auslandsstudiums mit dem Learning "
                           "Agreement - During the Mobility vornehmen."
    },
    {
        "description": "Informiere Dich mindestens sechs Monate im Voraus, ob Dir Auslands-BAföG zusteht.",
        "description_new": "Informiere Dich mindestens sechs Monate im Voraus, ob dir Auslands-BAföG zusteht."
    },
    {
        "description": "Finde heraus, ob du ein Visum oder Aufenthaltsberechtigung für das Gastland benötigst.",
        "description_new": "Finde heraus, ob du ein Visum oder eine Aufenthaltsberechtigung für das Gastland benötigst."
    },
    {
        "description": "Manche Gastuniversitäten bieten kostenlose Sprachkurse bei Ankunft an. Diese sind wertvoll, "
                       "um direkt Kontakte zu anderen Erasmus-Teilnehmern zu knüpfen. Dafür muss vorher allerdings ein "
                       "Einstufungstest durchgeführt werden. Suche solch einen Test auf der Webseite der Gastuniversität.",
        "description_new": "Manche Gastuniversitäten bieten kostenlose Sprachkurse bei Ankunft an. Diese sind wertvoll, "
                           "um direkt Kontakte zu anderen Erasmus-Teilnehmenden zu knüpfen. Dafür muss vorher allerdings ein "
                           "Einstufungstest durchgeführt werden. Suche solch einen Test auf der Webseite der Gastuniversität."
    },
    {
        "description": "Suche Dir eine passende Unterkunft. Damit kann Dir die Gastuniversität ggf. weiterhelfen.",
        "description_new": "Suche dir eine passende Unterkunft. Damit kann dir die Gastuniversität ggf. weiterhelfen."
    },
    {
        "title": "",
        "description": "Buche einen Flug und freu Dich auf die Reise. Wir wünschen Dir ein unvergessliches Abenteuer.",
        "title_new": "",
        "description_new": "Buche einen Flug und freu Dich auf die Reise. Wir wünschen dir ein unvergessliches Abenteuer."
    },
    {
        "title": "Email-Benachrichtigung",
        "title_new": "E-Mail-Benachrichtigung",
    },
    {
        "description": "Danke, dass du dir die Zeit nimmst, den Siddata-Prototypen vorab zu testen. Bitte teile "
                       "deine Eindrücke und Erfahrungen mit uns.<br>Möchtest du den <b>Fragebogen</b> beantworten?",
        "description_new": "Danke, dass du dir die Zeit nimmst, den Siddata-Prototypen zu testen. Wir "
                           "freuen uns, wenn du deine Erfahrungen und Eindrücke "
                           "mit uns teilst. Dazu haben wir einen Evaluations-Fragebogen vorbereitet.<br><br>"
                           "Möchtest du die Funktion Evaluation nutzen?"
    },
    {
        "description": ' Im Zuge einer wissenschaftlichen Arbeit wird gerade eine Begleitumfrage zu SIDDATA durchgeführt.'
                       ' Dort wollen wir untersuchen, wie deine Wahrnehmung der Nutzung von SIDDATA ist.'
                       ' Um an der Studie teilzunehmen klicke bitte hier: '
                       '<a href="https://www.survey.uni-osnabrueck.de/limesurvey/index.php/286649?lang=de">Zur Studie</a>',
        "description_new": ' Im Zuge einer wissenschaftlichen Arbeit wird gerade eine Begleitumfrage zu Siddata durchgeführt.'
                           ' Dort wollen wir untersuchen, wie deine Wahrnehmung der Nutzung von Siddata ist.'
                           ' Um an der Studie teilzunehmen, klicke bitte hier: '
                           '<a href="https://www.survey.uni-osnabrueck.de/limesurvey/index.php/286649?lang=de">Zur Studie</a>'
    },
    {
        "title": "Meine Visitenkarte",
        "title_new": "Deine Visitenkarte",
    },
    {
        "description": "Ein Klick auf den Button löst eine Aktualisierung anhand der aktuellen Daten aus. Dies "
                       "aktualisiert sowohl die Empfehlungen als auf das Formular selbst, beispielweise wenn du neue "
                       "Funktionen genutzt oder neue Eingaben vorgenommen hast.",
        "description_new": "Ein Klick auf den Button aktualisiert deine persönlichen Angaben und es werden neue Kontaktvorschläge "
                           "generiert."
    },
    {
        "description": "<p>Du hast mit dem Fragebogen deine Lernstrategien in vier Dimensionen evaluiert:"
                       " <strong>Kognitive Strategien</strong>, <strong>Metakognitive "
                       "Strategien</strong>, "
                       "<strong>Interne Ressourcen</strong> und <strong>Externe Ressourcen</strong>.</p> "
                       "<p>Kognitive Strategien umfassen diejenigen Prozesse, die du "
                       "einsetzt, "
                       "um dir den Lernstoff  zu erarbeiten und zu merken. "
                       "Dazu gehören unter anderem <strong>Organisieren</strong>, "
                       "<strong>Elaborieren</strong>, "
                       "<strong>Kritisches Prüfen</strong> sowie <strong>Wiederholen</strong>. "
                       "Elaborieren umfasst Studientätigkeiten, die auf ein "
                       "tieferes Verstehen des "
                       "Stoffes ausgerichtet sind.</p> "
                       "<p>Metakognitive Strategien dienen dazu, das eigene Lernen"
                       " zu <strong>planen</strong>, zu <strong>überwachen</strong> und zu "
                       "<strong>regulieren</strong>.</p> "
                       "<p>Interne Ressourcen bezeichnen deine Potentiale, "
                       "die du für dein Lernen mobilisierst. "
                       "Dazu gehören unter anderen <strong>Aufmerksamkeit</strong>, "
                       "<strong>Anstrengung</strong>, und "
                       "<strong>Zeitmanagement</strong>.</p> <p>Externe Ressourcen "
                       "bezeichnen günstige Rahmenbedingungen, "
                       "die du dir für dein Lernen schaffst, "
                       "insbesondere, deine <strong>Lernumgebung</strong>, "
                       "<strong>Lernen mit Studienkolleg*innen</strong> und "
                       "<strong>Literaturrecherche</strong>.</p> "
                       "<p>Im folgenden siehst du, wie du deinen Einsatz dieser Strategien "
                       "selbst eingeschätzt hast. Außerdem findest Empfehlungen für den künftigen Einsatz "
                       "dieser Strategien.</p>",
        "description_new": "<p>Du hast mit dem Fragebogen deine Lernstrategien in vier Dimensionen evaluiert:"
                           " <strong>Kognitive Strategien</strong>, <strong>Metakognitive " 
                           "Strategien</strong>, "
                           "<strong>Interne Ressourcen</strong> und <strong>Externe Ressourcen</strong>.</p> "
                           "<p>Kognitive Strategien umfassen diejenigen Prozesse, die du "
                           "einsetzt, "
                           "um dir den Lernstoff  zu erarbeiten und zu merken. "
                           "Dazu gehören unter anderem <strong>Organisieren</strong>, "
                           "<strong>Elaborieren</strong>, "
                           "<strong>Kritisches Prüfen</strong> sowie <strong>Wiederholen</strong>. "
                           "Elaborieren umfasst Studientätigkeiten, die auf ein "
                           "tieferes Verstehen des "
                           "Stoffes ausgerichtet sind.</p> "
                           "<p>Metakognitive Strategien dienen dazu, das eigene Lernen"
                           " zu <strong>planen</strong>, zu <strong>überwachen</strong> und zu "
                           "<strong>regulieren</strong>.</p> "
                           "<p>Interne Ressourcen bezeichnen deine Potentiale, "
                           "die du für dein Lernen mobilisierst. "
                           "Dazu gehören unter anderen <strong>Aufmerksamkeit</strong>, "
                           "<strong>Anstrengung</strong>, und "
                           "<strong>Zeitmanagement</strong>.</p> <p>Externe Ressourcen "
                           "bezeichnen günstige Rahmenbedingungen, "
                           "die du dir für dein Lernen schaffst, "
                           "insbesondere, deine <strong>Lernumgebung</strong>, "
                           "<strong>Lernen mit Mitstudierenden</strong> und "
                           "<strong>Literaturrecherche</strong>.</p> "
                           "<p>Im folgenden siehst du, wie du deinen Einsatz dieser Strategien "
                           "selbst eingeschätzt hast. Außerdem findest Empfehlungen für den künftigen Einsatz "
                           "dieser Strategien.</p>"
    },
    {
        "description": "1. Ich formuliere fachliche Fragen zu dem Thema und suche aktiv nach Antworten. "
                       "<br><br>2. Ich überlege mir, was ich schon über das Thema weiß und schreibe "
                       "dies in Stichworten auf oder mache mir dazu eine Skizze." + "<br>"
                       "<br>" + "3. Ich frage mich, was mich "
                       "persönlich an dem Thema interessiert oder interessieren könnte. ",
        "description_new": "1. Formuliere fachliche Fragen zu dem Thema und suche aktiv nach Antworten. " 
                           "<br><br>2. Überlege dir, was du schon über das Thema weißt und schreibe "
                           "dies in Stichworten auf oder mach dir dazu eine Skizze." + "<br>" 
                           "<br>" + "3. Was interessiert dich persönlich an dem Thema oder was könnte dich "
                           "interessieren?"
    },
    {
        "description": "1. Ich formuliere fachliche Fragen zu dem Thema und suche aktiv nach Antworten. ",
        "description_new": "1. Formuliere fachliche Fragen zu dem Thema und suche aktiv nach Antworten. "
    },
    {
        "description": "1. Ich überlege mir, was ich schon über das Thema weiß und schreibe dies in "
                       "Stichworten auf oder mache mir dazu eine Skizze. " + "<br>" + "<br>"
                       "2. Ich frage mich, was mich persönlich an dem Thema interessiert oder "
                       "interessieren könnte. ",
        "description_new": "1. Überlege dir, was du schon über das Thema weißt und schreibe dies in "
                           "Stichworten auf oder mach dir dazu eine Skizze. " + "<br>" + "<br>" 
                           "2. Frage dich, was dich persönlich an dem Thema interessiert oder "
                           "interessieren könnte. "
    },
    {
        "description": "1. Ich suche nach dem roten Faden: Was sind die Verbindungen zwischen den "
                       "wichtigen Gedanken und Fakten?" + "<br>" + "<br>"
                       "2. Ich denke intensiv über den Stoff nach und prüfe, "
                       "ob ich alles gut verstanden habe. Ich verschaffe mir einen Überblick, um von "
                       "einem allgemeinen Verständnis aus die Details besser zu verstehen." + "<br>"
                       "<br>" + "3. Ich schreibe den Stoff in meinen eigenen Worten auf (Paraphrasieren). ",
        "description_new": "1. Suche nach dem roten Faden: Was sind die Verbindungen zwischen den "
                           "wichtigen Gedanken und Fakten?" + "<br>" + "<br>"
                           "2. Denke intensiv über den Stoff nach und prüfe, "
                           "ob du alles gut verstanden hast. Verschaffe dir einen Überblick, um von "
                           "einem allgemeinen Verständnis aus die Details besser zu verstehen." + "<br>" 
                           "<br>" + "3. Schreibe den Stoff in deinen eigenen Worten auf (Paraphrasieren). "
    },
    {
        "description": "1. Ich suche nach dem roten Faden: Was sind die Verbindungen zwischen den "
                       "wichtigen "
                       "Gedanken und Fakten?" + "<br>" + "<br>"
                       "2. Ich denke intensiv über den Stoff nach und prüfe, ob ich "
                       "alles gut verstanden habe. ",
        "description_new": "1. Suche nach dem roten Faden: Was sind die Verbindungen zwischen den "
                           "wichtigen "
                           "Gedanken und Fakten?" + "<br>" + "<br>"
                           "2. Denke intensiv über den Stoff nach und prüfe, ob du "
                           "alles gut verstanden hast. "
    },
    {
        "description": "1. Ich suche nach dem roten Faden: Was sind die Verbindungen zwischen den "
                       "wichtigen Gedanken und Fakten?" + "<br>" + "<br>"
                       "2. Ich denke intensiv über den Stoff nach und prüfe, "
                       "ob ich alles gut verstanden habe." + "<br>" + "<br>"
                       "3. Ich gliedere den Stoff anhand vorhandener Strukturen." + "<br>" + "<br>"
                       "4. Ich achte darauf, sowohl Details zu verstehen als auch einen "
                       "Überblick zu erlangen.",
        "description_new": "1. Suche nach dem roten Faden: Was sind die Verbindungen zwischen den "
                           "wichtigen Gedanken und Fakten?" + "<br>" + "<br>"
                           "2. Denke intensiv über den Stoff nach und prüfe, "
                           "ob du alles gut verstanden hast." + "<br>" + "<br>"
                           "3. Gliedere den Stoff anhand vorhandener Strukturen." + "<br>" + "<br>"
                           "4. Achte darauf, sowohl Details zu verstehen als auch einen "
                           "Überblick zu erlangen."
    },
    {
        "description": "1. Ich stelle den Lernstoff regelmäßig in Bezug mit meinem Vorwissen." + "<br>" 
                       "<br>" + "2. Ich suche nach dem roten Faden: Was sind die Verbindungen zwischen "
                                "den wichtigen "
                                "Gedanken und Fakten?" + "<br>" + "<br>"
                       "3. Ich suche nach konkreten Beispielen und Anwendungen" + "<br>" + "<br>"
                       "4. Ich schreibe den Stoff in meinen eigenen Worten auf (Paraphrasieren).",
        "description_new": "1. Stelle den Lernstoff regelmäßig in Bezug mit deinem Vorwissen." + "<br>"
                           "<br>" + "2. Suche nach dem roten Faden: Was sind die Verbindungen zwischen "
                                    "den wichtigen "
                                    "Gedanken und Fakten?" + "<br>" + "<br>"
                           "3. Suche nach konkreten Beispielen und Anwendungen" + "<br>" + "<br>"
                           "4. Schreibe den Stoff in meinen eigenen Worten auf (Paraphrasieren)."
    },
    {
        "description": "1. Ich stelle den Lernstoff regelmäßig in Bezug mit meinem Vorwissen." + "<br>"
                       "<br>" + "2. Ich suche nach dem roten Faden: Was sind die Verbindungen "
                       "zwischen den wichtigen "
                       "Gedanken und Fakten?" + "<br>" + "<br>"
                       "3. Ich verschaffe mir einen Überblick, um von einem allgemeinen Verständnis aus die "
                       "Details besser zu verstehen." + "<br>" + "<br>"
                       "4. Ich schreibe den Stoff in meinen eigenen Worten auf (Paraphrasieren).",
        "description_new": "1. Stelle den Lernstoff regelmäßig in Bezug mit deinem Vorwissen." + "<br>"
                           "<br>" + "2. Suche nach dem roten Faden: Was sind die Verbindungen "
                           "zwischen den wichtigen "
                           "Gedanken und Fakten?" + "<br>" + "<br>"
                           "3. Verschaffe mir einen Überblick, um von einem allgemeinen Verständnis aus die "
                           "Details besser zu verstehen." + "<br>" + "<br>"
                           "4. Schreibe den Stoff in deinen eigenen Worten auf (Paraphrasieren)."
    },
    {
        "description": "1. Ich stelle den Lernstoff regelmäßig in Bezug mit meinem Vorwissen." + "<br>" 
                       "<br>" 
                       "2. Ich suche nach dem roten Faden: Was sind die Verbindungen zwischen "
                       "den wichtigen "
                       "Gedanken und Fakten?" + "<br>" + "<br>"
                       "3. Ich gliedere den Stoff anhand vorhandener Strukturen." + "<br>" + "<br>" 
                       "4. Ich achte darauf, sowohl Details zu verstehen als auch einen "
                       "Überblick zu erlangen.",
        "description_new": "1. Stelle den Lernstoff regelmäßig in Bezug mit deinem Vorwissen." + "<br>" 
                           "<br>"
                           "2. Suche nach dem roten Faden: Was sind die Verbindungen zwischen "
                           "den wichtigen "
                           "Gedanken und Fakten?" + "<br>" + "<br>" 
                           "3. Gliedere den Stoff anhand vorhandener Strukturen." + "<br>" + "<br>" 
                           "4. Achte darauf, sowohl Details zu verstehen als auch einen "
                           "Überblick zu erlangen."
    },
    {
        "description": "1. Ich frage mich, was mich persönlich an dem Thema interessiert oder "
                       "interessieren könnte. " + "<br>" + "<br>"
                       "2. Ich schreibe den Stoff in meinen eigenen Worten auf (Paraphrasieren).",
        "description_new": "1. Frage dich, was dich persönlich an dem Thema interessiert oder "
                           "interessieren könnte. " + "<br>" + "<br>"
                           "2. Schreibe den Stoff in deinen eigenen Worten auf (Paraphrasieren)."
    },
    {
        "description": "1. Ich verschaffe mir einen Überblick, um von einem allgemeinen Verständnis "
                       "aus die Details besser zu verstehen." + "<br>" + "<br>"
                       "2. Ich schreibe den Stoff in meinen eigenen Worten auf (Paraphrasieren).",
        "description_new": "1. Verschaffe dir einen Überblick, um von einem allgemeinen Verständnis "
                           "aus die Details besser zu verstehen." + "<br>" + "<br>"
                           "2. Schreibe den Stoff in deinen eigenen Worten auf (Paraphrasieren)."
    },
    {
        "description": "1. Ich gliedere den Stoff anhand vorhandener Strukturen." + "<br>" + "<br>"
                       "2. Ich achte darauf, sowohl Details zu verstehen als auch einen "
                       "Überblick zu erlangen.",
        "description_new": "1. Gliedere den Stoff anhand vorhandener Strukturen." + "<br>" + "<br>"
                           "2. Achte darauf, sowohl Details zu verstehen als auch einen "
                           "Überblick zu erlangen."
    },
    {
        "description": "1. Ich schreibe mir in meinen eigenen Worten eine kurze Zusammenfassung der "
                      "wichtigsten Inhalte, ohne dabei in meine Aufzeichnungen oder in Bücher zu schauen."
                      + "<br>" + "<br>" + "2. Ich erkläre Kommiliton*innen den Stoff. " + "<br>" + "<br>"
                      + "3. Während ich den Stoff einer anderen "
                      "Person erkläre, identifiziere ich Verständnis- und Erinnerungslücken und "
                      "arbeite diese auf." + "<br>" + "<br>" + "4. Ich stelle mir vor, wie ich einem "
                                                               "Freund oder einer Freundin den Stoff erklären würde. ",
        "description_new": "1. Schreibe dir in deinen eigenen Worten eine kurze Zusammenfassung der "
                           "wichtigsten Inhalte, ohne dabei in deine Aufzeichnungen oder in Bücher zu schauen."
                           + "<br>" + "<br>" + "2. Erkläre Mitstudierenden den Stoff. " + "<br>" + "<br>"
                           + "3. Während du den Stoff einer anderen "
                           "Person erklärst, identifizierst du Verständnis- und Erinnerungslücken und "
                           "arbeitest diese auf." + "<br>" + "<br>"
    },
    {
        "description": "1. Ich schreibe mir in meinen eigenen Worten eine kurze Zusammenfassung der "
                       "wichtigsten Inhalte, ohne dabei in meine Aufzeichnungen oder in Bücher zu schauen."
                       + "<br>" + "<br>" + "2. Ich erkläre Kommiliton*innen den Stoff." + "<br>" + "<br>"
                       "3. Während ich den Stoff einer anderen Person erkläre, identifiziere ich "
                       "Verständnis- und Erinnerungslücken und arbeite diese auf.",
        "description_new": "1. Schreibe dir in deinen eigenen Worten eine kurze Zusammenfassung der "
                           "wichtigsten Inhalte, ohne dabei in deine Aufzeichnungen oder in Bücher zu schauen."
                           + "<br>" + "<br>" + "2. Erkläre Mitstudierenden den Stoff." + "<br>" + "<br>"
                           "3. Während du den Stoff einer anderen Person erklärst, identifizierst du "
                           "Verständnis- und Erinnerungslücken und arbeitest diese auf."
    },
    {
        "description": "1. Ich formuliere wichtige Gedanken in Merksätzen und rufe mir diese regelmäßig "
                       "in Erinnerung - ohne dabei in meine Unterlagen zu schauen."
                       + "<br>" + "<br>" + "2. Ich erkläre Kommiliton*innen den Stoff." + "<br>" + "<br>"
                       "3. Während ich den Stoff einer anderen Person erkläre, identifiziere ich "
                       "Verständnis- und Erinnerungslücken und arbeite diese auf." + "<br>" + "<br>"
                       "4. Ich stelle mir vor, wie ich einem Freund oder einer Freundin den "
                       "Stoff erklären würde.",
        "description_new": "1. Formuliere wichtige Gedanken in Merksätzen und rufe dir diese regelmäßig "
                           "in Erinnerung - ohne dabei in deine Unterlagen zu schauen."
                           + "<br>" + "<br>" + "2. Erkläre Mitstudierenden den Stoff." + "<br>" + "<br>"
                           "3. Während du den Stoff einer anderen Person erklärst, identifizierst du "
                           "Verständnis- und Erinnerungslücken und arbeitest diese auf."
    },
    {
        "description": "1. Ich formuliere wichtige Gedanken in Merksätzen und rufe mir diese regelmäßig "
                       "in Erinnerung - ohne dabei in meine Unterlagen zu schauen."
                       + "<br>" + "<br>" + "2. Ich erkläre Kommiliton*innen den Stoff." + "<br>" + "<br>"
                       "3. Während ich den Stoff einer anderen Person erkläre, identifiziere ich "
                       "Verständnis- und Erinnerungslücken und arbeite diese auf.",
        "description_new": "1. Formuliere wichtige Gedanken in Merksätzen und rufe dir diese regelmäßig "
                           "in Erinnerung - ohne dabei in deine Unterlagen zu schauen."
                           + "<br>" + "<br>" + "2. Erkläre Mitstudierenden den Stoff." + "<br>" + "<br>"
                           "3. Während du den Stoff einer anderen Person erklärst, identifizierst du "
                           "Verständnis- und Erinnerungslücken und arbeitest diese auf."
    },
    {
        "description": "1. Ich versuche nachzuvollziehen, auf welchem Wege das Wissen zustande gekommen "
                       "ist (beispielsweise durch mathematische Beweise, philosophische Argumentationen "
                       "oder durch naturwissenschaftliche Experimente)." + "<br>" + "<br>"
                       "2. Ich denke mir Prüfungsfragen zum Stoff aus und versuche diese zu beantworten."
                       "<br>" + "<br>" + "3. Ich stelle mir vor, wie ich einem Freund oder "
                                         "einer Freundin den Stoff erklären würde.",
        "description_new": "1. Versuche nachzuvollziehen, auf welchem Wege das Wissen zustande gekommen "
                           "ist (beispielsweise durch mathematische Beweise, philosophische Argumentationen "
                           "oder durch naturwissenschaftliche Experimente)." + "<br>" + "<br>" 
                           "2. Denke dir Prüfungsfragen zum Stoff aus und versuche diese zu beantworten."
    },
    {
        "description": "1. Ich versuche nachzuvollziehen, auf welchem Wege das Wissen zustande gekommen "
                       "ist (beispielsweise durch mathematische Beweise, philosophische Argumentationen "
                       "oder durch naturwissenschaftliche Experimente)." + "<br>" + "<br>"
                       + "2. Ich denke mir Prüfungsfragen zum Stoff aus und versuche diese zu beantworten.",
        "description_new": "1. Versuche nachzuvollziehen, auf welchem Wege das Wissen zustande gekommen "
                           "ist (beispielsweise durch mathematische Beweise, philosophische Argumentationen "
                           "oder durch naturwissenschaftliche Experimente)." + "<br>" + "<br>"
                           + "2. Denke dir Prüfungsfragen zum Stoff aus und versuche diese zu beantworten.",
    },
    {
        "description": "Deinen Regelstudienplan kennst du. Darüber hinaus gibt es eine Menge an interessanten "
                       "Veranstaltungen und Angeboten, von denen du vielleicht noch gar nichts weißt. SIDDATA kann "
                       "diese für dich finden, wenn du etwas über deine Interessen - auch über dein Studium hinaus"
                       " - eingibst.",
        "description_new": "Deinen Regelstudienplan kennst du. Darüber hinaus gibt es eine Menge an interessanten "
                           "Veranstaltungen und Angeboten, von denen du vielleicht noch gar nichts weißt. Siddata kann "
                           "diese für dich finden, wenn du etwas über deine Interessen - auch über dein Studium hinaus"
                           " - eingibst."
    },
    {
        "description": 'Zur Zeit gibt es leider keine Bildungsressourcen,'
                       ' die deinem Interesse entsprechen.'
                       ' SIDDATA wird dich an einem späteren Zeitpunkt noch einmal informieren,'
                       ' sobald neue Ressourcen für dich gefunden wurden.',
        "description_new": 'Zur Zeit gibt es leider keine Bildungsressourcen,'
                           ' die deinem Interesse entsprechen.'
                           ' Siddata wird dich an einem späteren Zeitpunkt noch einmal informieren,'
                           ' sobald neue Ressourcen für dich gefunden wurden.'
    },
    {
        "description": "<strong>Was ist der Unterschied zwischen meinem Studienfach und meinen"
                       " fachlichen Interessen? </strong> <br>"
                       "Deine fachlichen Interessen sollten im Idealfall der Grund sein, warum Du das Fach,"
                       " was Du studierst, gewählt hast. Persönliche fachliche Interessen machen in der"
                       " Regel aber nur ein Teilgebiet Deines Studienfaches aus und gehen im Idealfall"
                       " darüber hinaus. SIDDATA hilft Dir, Veranstaltungen zu finden, die stärker"
                       " Deinen persönlichen fachlichen Interessen entsprechen. <br> <br>"
                       " <strong> Warum ist es wichtig, sich über seine fachlichen Interessen im Klaren zu sein? </strong>"
                       "In vielen Kontexten - z.B. in Bewerbungsgesprächen, auf Parties, beim Kennenlernen"
                       " - ist es hilfreich wenn Du Deine eigenen Interessen klar und knapp"
                       " kommunizieren kannst. Zudem hilft es Dir das Thema deiner Abschlussarbeit,"
                       " ein Nebenfach oder eine Vertiefungsrichtung zu wählen. Auch für die Wahl"
                       " von geeigneten Praktika oder Auslandsaufenthalten kann es hilfreich sein.",
        "description_new": "<strong>Was ist der Unterschied zwischen meinem Studienfach und meinen"
                           " fachlichen Interessen? </strong> <br>"
                           "Deine fachlichen Interessen sollten im Idealfall der Grund sein, warumdudas Fach,"
                           " wasdustudierst, gewählt hast. Persönliche fachliche Interessen machen in der"
                           " Regel aber nur ein Teilgebietdeines Studienfaches aus und gehen im Idealfall"
                           " darüber hinaus. Siddata hilft dir Veranstaltungen zu finden, die stärker"
                           "deinen persönlichen fachlichen Interessen entsprechen. <br> <br>"
                           " <strong> Warum ist es wichtig, sich über seine fachlichen Interessen im Klaren "
                           "zu sein? </strong>"
                           "In vielen Kontexten, z.B. in Bewerbungsgesprächen, ist es hilfreich, wenn du "
                           "deine eigenen Interessen klar kommunizieren kannst. Auch bei der Wahl deines "
                           "Abschlussarbeitsthemas, eines Nebenfachs, einer Vertiefungsrichtung oder auch "
                           "bei der Suche nach geeigneten Praktika und Auslandsaufenthalten, kann es dir "
                           "helfen, deinen fachlichen Interessen bewusst zu sein. "
    },
    {
        "description": "Informationen und Empfehlungen werden dir in Siddata in Boxen wie dieser dargestellt.<br>"
                       "Du kannst diese entweder abschließen, pausieren oder verwerfen.<br>"
                       "Über die entsprechenden Ansichten (links unter der Navigation) kannst du die Boxen "
                       "bei Bedarf wieder aufnehmen.<br>"
                       "So lange eine Box nicht von dir bearbeitet wurde, ist sie offen.<br>"
                       "Über die Buttons unten in jeder Box kannst du diese als abgeschlossen markieren.<br>"
                       'Möchtest du eine Box später bearbeiten, kannst du sie über das Icon "Pausieren" '
                       'zurückstellen.<br>'
                       "Wenn du den Inhalt einer Box nicht sinnvoll findest, kannst du sie über das Icon Verwerfen "
                       "aussortieren.",
        "description_new": "Informationen und Empfehlungen werden dir in Siddata in Boxen wie "
                           "dieser dargestellt. Du kannst diese entweder "
                           "abschließen, pausieren oder verwerfen. Über die "
                           "entsprechenden Ansichten (links unter der Navigation) kannst du die "
                           "Boxen bei Bedarf wieder aufnehmen.<br>"
                           "So lange eine Box nicht von dir bearbeitet wurde, ist sie offen.<br>"
                           "Über die Buttons unten in jeder Box kannst du diese als abgeschlossen "
                           "markieren. Möchtest du eine Box später bearbeiten, kannst du sie über das "
                           "Icon \"Pausieren\" zurückstellen. Wenn du den Inhalt einer Box nicht sinnvoll "
                           "findest, kannst du sie über das Icon \"Verwerfen\" aussortieren."
    },
    {
        "description": "Mit Siddata kannst du dich zum Beispiel mit anderen Studierenden vernetzen, mehr über "
                       "dein Lernverhalten erfahren und Veranstaltungen an anderen Universitäten besuchen. "
                       "Dazu kannst du verschiedene Funktionen/Tools aktivieren.<br><br>Im Folgenden werden "
                       "dir alle Funktionen kurz beschrieben. Bitte entscheide dich zunächst, welche "
                       "Funktionen du ausprobieren möchtest. Wenn du deine Meinung änderst, kannst du in "
                       "den Einstellungen jederzeit Funktionen aktivieren oder deaktivieren.",
        "description_new": "Mit Siddata kannst du dich zum Beispiel mit anderen Studierenden "
                           "vernetzen, mehr über dein Lernverhalten erfahren und Veranstaltungen "
                           "an anderen Universitäten besuchen. Dazu kannst du verschiedene "
                           "Funktionen aktivieren.<br><br>"
                           "Im Folgenden werden dir alle Funktionen kurz beschrieben. Bitte "
                           "entscheide dich zunächst, welche Funktionen du ausprobieren "
                           "möchtest. Wenn du deine Meinung änderst, kannst du in den "
                           "Einstellungen jederzeit Funktionen aktivieren oder deaktivieren."
    },
    {
        "title": "Universitätsbibliothek",
        "description": "Wenn du dir Literatur ausleihen möchtest, kann dir die Bibliothek deiner Universität"
                       "helfen. <a href='https://www.ub.uni-osnabrueck.de/startseite.html' target='_blank'>Hier "
                       "geht es zur" 
                       "Website.</a>",
        "title_new": "Universitätsbibliothek",
        "description_new": "Wenn du dir Literatur ausleihen möchtest, kann dir die Bibliothek deiner Universität"
                           "helfen. <a href='https://www.ub.uni-osnabrueck.de/startseite.html' target='_blank'>Hier "
                           "geht es zur " 
                           "Website.</a>"
    },
    {
        "title": "Universitätsbibliothek",
        "description": "Wenn du dir Literatur ausleihen möchtest, kann dir die Bibliothek deiner Universität" 
                       "helfen. <a href='https://www.suub.uni-bremen.de/' target='_blank'>Hier geht es zur"
                       "Website.</a>",
        "title_new": "Universitätsbibliothek",
        "description_new": "Wenn du dir Literatur ausleihen möchtest, kann dir die Bibliothek deiner Universität" 
                           "helfen. <a href='https://www.suub.uni-bremen.de/' target='_blank'>Hier geht es zur "
                           "Website.</a>"
    },
    {
        "title": "Universitätsbibliothek",
        "description": "Wenn du dir Literatur ausleihen möchtest, kann dir die Bibliothek deiner Universität" 
                       "helfen. <a href='https://www.tib.eu/de/' target='_blank'>Hier geht es zur"
                       "Website.</a>",
        "title_new": "Universitätsbibliothek",
        "description_new": "Wenn du dir Literatur ausleihen möchtest, kann dir die Bibliothek deiner Universität" 
                           "helfen. <a href='https://www.tib.eu/de/' target='_blank'>Hier geht es zur "
                           "Website.</a>"
    },
    {
        "title": "Lern- und Gruppenarbeitsräume",
        "description": "Wenn du einen ruhigen Platz zum Arbeiten suchst oder einen Ort für Gruppenarbeiten"
                       " benötigst, kannst du dir hier einen Raum buchen."
                       "<a href='https://www.ub.uni-osnabrueck.de/startseite.html'"
                       "target='_blank'>Hier geht es zur "    
                       "Website.</a>",
        "title_new": "Lern- und Gruppenarbeitsräume",
        "description_new": "Wenn du einen ruhigen Platz zum Arbeiten suchst oder einen Ort für Gruppenarbeiten"
                           " benötigst, kannst du dir hier einen Raum buchen. "
                           "<a href='https://www.ub.uni-osnabrueck.de/startseite.html'"
                           "target='_blank'>Hier geht es zur "    
                           "Website.</a>"
    },
    {
        "title": "Lern- und Gruppenarbeitsräume",
        "description": "Wenn du einen ruhigen Platz zum Arbeiten suchst oder einen Ort für Gruppenarbeiten"
                       " benötigst,kannst du dir hier einen Raum buchen."
                       "<a href='https://www.uni-bremen.de/universitaet/campus/lernraeume'"
                       "target='_blank'>Hier geht es zur "
                       "Website.</a>",
        "title_new": "Lern- und Gruppenarbeitsräume",
        "description_new": "Wenn du einen ruhigen Platz zum Arbeiten suchst oder einen Ort für Gruppenarbeiten"
                           " benötigst,kannst du dir hier einen Raum buchen. "
                           "<a href='https://www.uni-bremen.de/universitaet/campus/lernraeume'"
                           "target='_blank'>Hier geht es zur "
                           "Website.</a>"
    },
    {
        "title": "Lern- und Gruppenarbeitsräume",
        "description": "Wenn du einen ruhigen Platz zum Arbeiten suchst oder einen Ort für Gruppenarbeiten"
                       " benötigst,kannst du dir hier einen Raum buchen."
                       "<a href='https://www.zqs.uni-hannover.de/de/qs/lernraum/'"
                       "target='_blank'>Hier geht es zur "
                       "Website.</a>",
        "title_new": "Lern- und Gruppenarbeitsräume",
        "description_new": "Wenn du einen ruhigen Platz zum Arbeiten suchst oder einen Ort für Gruppenarbeiten"
                           " benötigst,kannst du dir hier einen Raum buchen. "
                           "<a href='https://www.zqs.uni-hannover.de/de/qs/lernraum/'"
                           "target='_blank'>Hier geht es zur "
                           "Website.</a>"
    },
    {
        "title": "Wenn es mal nicht so läuft...",
        "description": "Schwierige Phasen erlebt jeder einmal, im Studium und im Privaten."
                       " Nicht immer lassen sich diese Hindernisse schnell und aus eigener Kraft überwinden."
                       " Wenn du in einer solchen Phase bist, scheue dich nicht Hilfe anzunehmen."
                       "<a href='https://www.studentenwerk-osnabrueck.de/de/beratung/"
                       "psychologische-beratung.html' "
                       "target='_blank'>Hier geht es zur Website.</a>",
        "title_new": "Wenn es mal nicht so läuft...",
        "description_new": "Schwierige Phasen erlebt jeder einmal, im Studium und im Privaten."
                           " Nicht immer lassen sich diese Hindernisse schnell und aus eigener Kraft überwinden."
                           " Wenn du in einer solchen Phase bist, scheue dich nicht Hilfe anzunehmen. "
                           "<a href='https://www.studentenwerk-osnabrueck.de/de/beratung/"
                           "psychologische-beratung.html' "
                           "target='_blank'>Hier geht es zur Website.</a>"
    },
    {
        "title": "Wenn es mal nicht so läuft...",
        "description": "Schwierige Phasen erlebt jeder einmal, im Studium und im Privaten."
                       " Nicht immer lassen sich diese Hindernisse schnell und aus eigener Kraft überwinden."
                       " Wenn du in einer solchen Phase bist, scheue dich nicht Hilfe anzunehmen."
                       "<a href='https://www.stw-bremen.de/de/beratung/psychologische-beratung'"
                       "target='_blank'>Hier geht es zur Website.</a>",
        "title_new": "Wenn es mal nicht so läuft...",
        "description_new": "Schwierige Phasen erlebt jeder einmal, im Studium und im Privaten."
                           " Nicht immer lassen sich diese Hindernisse schnell und aus eigener Kraft überwinden."
                           " Wenn du in einer solchen Phase bist, scheue dich nicht Hilfe anzunehmen. "
                           "<a href='https://www.stw-bremen.de/de/beratung/psychologische-beratung'"
                           "target='_blank'>Hier geht es zur Website.</a>"
    },
    {
        "title": "Wenn es mal nicht so läuft...",
        "description": "Schwierige Phasen erlebt jeder einmal, im Studium und im Privaten."
                       " Nicht immer lassen sich diese Hindernisse schnell und aus eigener Kraft überwinden."
                       " Wenn du in einer solchen Phase bist, scheue dich nicht Hilfe anzunehmen."
                       "<a href='https://www.ptb.uni-hannover.de/'"
                       "target='_blank'>Hier geht es zur Website.</a>",
        "title_new": "Wenn es mal nicht so läuft...",
        "description_new": "Schwierige Phasen erlebt jeder einmal, im Studium und im Privaten."
                           " Nicht immer lassen sich diese Hindernisse schnell und aus eigener Kraft überwinden."
                           " Wenn du in einer solchen Phase bist, scheue dich nicht Hilfe anzunehmen. "
                           "<a href='https://www.ptb.uni-hannover.de/'"
                           "target='_blank'>Hier geht es zur Website.</a>"
    },
    {
        "title": "Sprachen lernen",
        "description": "Möchtest du eine neue Fremdsprache lernen oder deine Kenntnisse auffrischen?"
                       " Das Fremdsprachenangebot an Grund-, Aufbau- und Vertiefungskursen findest du hier:"
                       "<a href='https://www.uni-osnabrueck.de/universitaet/organisation/"
                       "zentrale-einrichtungen/sprachenzentrum/'",
        "title_new": "Sprachen lernen",
        "description_new": "Möchtest du eine neue Fremdsprache lernen oder deine Kenntnisse auffrischen?"
                           " Das Fremdsprachenangebot an Grund-, Aufbau- und Vertiefungskursen findest du hier: "
                           "<a href='https://www.uni-osnabrueck.de/universitaet/organisation/"
                           "zentrale-einrichtungen/sprachenzentrum/'"
    },
    {
        "title": "Sprachen lernen",
        "description": "Möchtest du eine neue Fremdsprache lernen oder deine Kenntnisse auffrischen?"
                       " Das Fremdsprachenangebot an Grund-, Aufbau- und Vertiefungskursen findest du hier:"
                       "<a href='https://www.fremdsprachenzentrum-bremen.de/'"
                       "target='_blank'>Hier geht es zur Website.</a>",
        "title_new": "Sprachen lernen",
        "description_new": "Möchtest du eine neue Fremdsprache lernen oder deine Kenntnisse auffrischen?"
                           " Das Fremdsprachenangebot an Grund-, Aufbau- und Vertiefungskursen findest du hier: "
                           "<a href='https://www.fremdsprachenzentrum-bremen.de/'"
                           "target='_blank'>Hier geht es zur Website.</a>"
    },
    {
        "title": "Sprachen lernen",
        "description": "Möchtest du eine neue Fremdsprache lernen oder deine Kenntnisse auffrischen?"
                       " Das Fremdsprachenangebot an Grund-, Aufbau- und Vertiefungskursen findest du hier:"
                       "<a href='https://www.llc.uni-hannover.de/'"
                       "target='_blank'>Hier geht es zur Website.</a>",
        "title_new": "Sprachen lernen",
        "description_new": "Möchtest du eine neue Fremdsprache lernen oder deine Kenntnisse auffrischen?"
                           " Das Fremdsprachenangebot an Grund-, Aufbau- und Vertiefungskursen findest du hier: "
                           "<a href='https://www.llc.uni-hannover.de/'"
                           "target='_blank'>Hier geht es zur Website.</a>"
    },
    {
        "title": "Sportangebote",
        "description": "Jedes Semester stehen dir zahlreiche Sportangebote im Rahmen des Hochschulsports zur "
                       "Verfügung.<a href='https://www.zfh.uni-osnabrueck.de/startseite.html'"
                       "target='_blank'>Hier geht es zur Website.</a>",
        "title_new": "Sportangebote",
        "description_new": "Jedes Semester stehen dir zahlreiche Sportangebote im Rahmen des Hochschulsports zur "
                           "Verfügung. <a href='https://www.zfh.uni-osnabrueck.de/startseite.html'"
                           "target='_blank'>Hier geht es zur Website.</a>"
    },
    {
        "title": "Sportangebote",
        "description": "Jedes Semester stehen dir zahlreiche Sportangebote im Rahmen des Hochschulsports zur "
                       "Verfügung.<a href='https://www.uni-bremen.de/hospo'"
                       "target='_blank'>Hier geht es zur Website.</a>",
        "title_new": "Sportangebote",
        "description_new": "Jedes Semester stehen dir zahlreiche Sportangebote im Rahmen des Hochschulsports zur "
                           "Verfügung. <a href='https://www.uni-bremen.de/hospo'"
                           "target='_blank'>Hier geht es zur Website.</a>"
    },
    {
        "title": "Sportangebote",
        "description": "Jedes Semester stehen dir zahlreiche Sportangebote im Rahmen des Hochschulsports zur "
                       "Verfügung.<a href='https://www.hochschulsport-hannover.de/'"
                       "target='_blank'>Hier geht es zur Website.</a>",
        "title_new": "Sportangebote",
        "description_new": "Jedes Semester stehen dir zahlreiche Sportangebote im Rahmen des Hochschulsports zur "
                           "Verfügung. <a href='https://www.hochschulsport-hannover.de/'"
                           "target='_blank'>Hier geht es zur Website.</a>"
    },
    {
        "title": "International Office",
        "description": "Wenn du dich für einen Studienaufenthalt im Ausland interessiert, erhältst du hier "
                       "Informationen und Unterstützung bei der Planung."
                       "<a href='https://www.uni-osnabrueck.de/universitaet/organisation/studentisches/"
                       "international-office/' target='_blank'>Hier geht es zur Website.</a>",
        "title_new": "International Office",
        "description_new": "Wenn du dich für einen Studienaufenthalt im Ausland interessiert, erhältst du hier "
                           "Informationen und Unterstützung bei der Planung. "
                           "<a href='https://www.uni-osnabrueck.de/universitaet/organisation/studentisches/"
                           "international-office/' target='_blank'>Hier geht es zur Website.</a>"
    },
    {
        "title": "International Office",
        "description": "Wenn du dich für einen Studienaufenthalt im Ausland interessiert, erhältst du hier "
                       "Informationen und Unterstützung bei der Planung."
                       "<a href='https://www.uni-bremen.de/universitaet/profil/international/"
                       "international-office' target='_blank'>Hier geht es zur Website.</a>",
        "title_new": "International Office",
        "description_new": "Wenn du dich für einen Studienaufenthalt im Ausland interessiert, erhältst du hier "
                           "Informationen und Unterstützung bei der Planung. "
                           "<a href='https://www.uni-bremen.de/universitaet/profil/international/"
                           "international-office' target='_blank'>Hier geht es zur Website.</a>"
    },
    {
        "title": "International Office",
        "description": "Wenn du dich für einen Studienaufenthalt im Ausland interessiert, erhältst du hier "
                       "Informationen und Unterstützung bei der Planung."
                       "<a href='https://www.uni-hannover.de/de/universitaet/internationales/'"
                       "_blank'>Hier geht es zur Website.</a>",
        "title_new": "International Office",
        "description_new": "Wenn du dich für einen Studienaufenthalt im Ausland interessiert, erhältst du hier "
                           "Informationen und Unterstützung bei der Planung. "
                           "<a href='https://www.uni-hannover.de/de/universitaet/internationales/'"
                           "_blank'>Hier geht es zur Website.</a>"
    },
    {
        "title": "Rechenzentrum",
        "description": "Bei technischen Fragen (z.B. zu deinem Uni-Account, zum WLAN) findest du hier "
                       "Informationen und Hilfestellungen."
                       "<ul> <li><a href='https://www.rz.uni-osnabrueck.de/' target='_blank'>"
                       "Hier geht es zur Website.</a></li>"
                       "<li><a href='https://www.rz.uni-osnabrueck.de/dienste/leitfaden/"
                       "leitfaden_studierende.html' target='_blank'>Hier geht es zur Website.</a></li></ul>",
        "title_new": "Rechenzentrum",
        "description_new": "Bei technischen Fragen (z.B. zu deinem Uni-Account, zum WLAN) findest du hier "
                           "Informationen und Hilfestellungen."
                           "<ul> <li><a href='https://www.rz.uni-osnabrueck.de/' target='_blank'>"
                           "Hier geht es zur Website des Rechenzentrums.</a></li>"
                           "<li><a href='https://www.rz.uni-osnabrueck.de/dienste/leitfaden/"
                           "leitfaden_studierende.html' target='_blank'>Hier geht es zu einem Leitfaden für "
                           "Erstsemester</a></li></ul>"
    },
    {
        "title": "Rechenzentrum",
        "description": "Bei technischen Fragen (z.B. zu deinem Uni-Account, zum WLAN) findest du hier "
                       "Informationen und Hilfestellungen."
                       "<a href='https://www.uni-bremen.de/zfn' target='_blank'>"
                       "Hier geht es zur Website.</a>",
        "title_new": "Rechenzentrum",
        "description_new": "Bei technischen Fragen (z.B. zu deinem Uni-Account, zum WLAN) findest du hier "
                           "Informationen und Hilfestellungen. "
                           "<a href='https://www.uni-bremen.de/zfn' target='_blank'>"
                           "Hier geht es zur Website.</a>"
    },
    {
        "title": "Rechenzentrum",
        "description": "Bei technischen Fragen (z.B. zu deinem Uni-Account, zum WLAN) findest du hier "
                       "Informationen und Hilfestellungen."
                       "<a href='https://www.luis.uni-hannover.de/' target='_blank'>"
                       "Hier geht es zur Website.</a>",
        "title_new": "Rechenzentrum",
        "description_new": "Bei technischen Fragen (z.B. zu deinem Uni-Account, zum WLAN) findest du hier "
                           "Informationen und Hilfestellungen. "
                           "<a href='https://www.luis.uni-hannover.de/' target='_blank'>"
                           "Hier geht es zur Website.</a>"
    },
    {
        "title": "Studierendensekretariat",
        "description": "Das Studierendensekretariat ist zuständig für die den Studierendenstatus betreffenden "
                       "administrativen Vorgänge während der gesamten Studienzeit z.B. der Rückmeldung, der "
                       "Campuscard oder der Beurlaubung."
                       "<a href='https://www.uni-bremen.de/sfs' target='_blank'> Hier geht es zur Website.",
        "title_new": "Studierendensekretariat",
        "description_new": "Das Studierendensekretariat ist zuständig für die den Studierendenstatus betreffenden "
                           "administrativen Vorgänge während der gesamten Studienzeit z.B. der Rückmeldung, der "
                           "Campuscard oder der Beurlaubung. "
                           "<a href='https://www.uni-bremen.de/sfs' target='_blank'> Hier geht es zur Website."
    },
    {
        "title": "Studierendensekretariat",
        "description": "Das Studierendensekretariat ist zuständig für die den Studierendenstatus betreffenden "
                       "administrativen Vorgänge während der gesamten Studienzeit z.B. der Rückmeldung, der "
                       "Campuscard oder der Beurlaubung."
                       "<a href='https://www.uni-hannover.de/de/studium/beratung-und-hilfe/servicecenter/'"
                       " target='_blank'> Hier geht es zur Website.",
        "title_new": "Studierendensekretariat",
        "description_new": "Das Studierendensekretariat ist zuständig für die den Studierendenstatus betreffenden "
                           "administrativen Vorgänge während der gesamten Studienzeit z.B. der Rückmeldung, der "
                           "Campuscard oder der Beurlaubung. "
                           "<a href='https://www.uni-hannover.de/de/studium/beratung-und-hilfe/servicecenter/'"
                           " target='_blank'> Hier geht es zur Website."
    },
    {
        "title": "Finanzierung und Förderung",
        "description": "Hier findest du Informationen rund um die Finanzierung deines Studiums z.B. "
                       "zum BAföG oder zu Stipendienprogrammen:"
                       "<a href='https://www.uni-hannover.de/de/studium/finanzierung-foerderung/'"
                       "target='_blank'>Hier geht es zur Website.</a>",
        "title_new": "Finanzierung und Förderung",
        "description_new": "Hier findest du Informationen rund um die Finanzierung deines Studiums z.B. "
                           "zum BAföG oder zu Stipendienprogrammen: "
                           "<a href='https://www.uni-hannover.de/de/studium/finanzierung-foerderung/'"
                           "target='_blank'>Hier geht es zur Website.</a>"
    },
    {
        "title": "Digitalisierung von Studium und Lehre",
        "description": "Bei Fragen rund um das Thema digitale Medien in Studium und Lehre (z.B. zu Stud.IP) "
                       "findest du hier Informationen und Hilfestellungen:"
                       "<a href='https://www.virtuos.uni-osnabrueck.de"
                       "zentrum_fuer_digitale_lehre_campus_management_"
                       "und_hochschuldidaktik.html' target='_blank'>Hier geht es zur Website.</a>",
        "title_new": "Digitalisierung von Studium und Lehre",
        "description_new": "Bei Fragen rund um das Thema digitale Medien in Studium und Lehre (z.B. zu Stud.IP) "
                           "findest du hier Informationen und Hilfestellungen: "
                           "<a href='https://www.virtuos.uni-osnabrueck.de/zentrum_fuer_digitale_lehre_campus_"
                           "management_und_hochschuldidaktik.html' target='_blank'>Hier geht es zur Website.</a>"
    },
    {
        "title": "Digitalisierung von Studium und Lehre",
        "description": "Bei Fragen rund um das Thema digitale Medien in Studium und Lehre (z.B. zu Stud.IP) "
                       "findest du hier Informationen und Hilfestellungen:"
                       "<a href='https://www.uni-bremen.de/zmml' target='_blank'>Hier geht es zur Website.</a>",
        "title_new": "Digitalisierung von Studium und Lehre",
        "description_new": "Bei Fragen rund um das Thema digitale Medien in Studium und Lehre (z.B. zu Stud.IP) "
                           "findest du hier Informationen und Hilfestellungen: "
                           "<a href='https://www.uni-bremen.de/zmml' target='_blank'>Hier geht es zur Website.</a>"
    },
    {
        "title": "Digitalisierung von Studium und Lehre",
        "description": "Bei Fragen rund um das Thema digitale Medien in Studium und Lehre (z.B. zu Stud.IP) "
                       "findest du hier Informationen und Hilfestellungen:"
                       "<a href='https://www.zqs.uni-hannover.de/de/elsa/'"
                       " target='_blank'>Hier geht es zur Website.</a>",
        "title_new": "Digitalisierung von Studium und Lehre",
        "description_new": "Bei Fragen rund um das Thema digitale Medien in Studium und Lehre (z.B. zu Stud.IP) "
                           "findest du hier Informationen und Hilfestellungen: "
                           "<a href='https://www.zqs.uni-hannover.de/de/elsa/'"
                           " target='_blank'>Hier geht es zur Website.</a>"
    },
    {
        "title": "Studieren mit Familie",
        "description": "Alle Informationen rund um das Thema Studieren mit Familie (z.B. Kinderbetreuung, "
                       "Pflege von Angehörigen) findest du hier:"
                       "<a href='https://www.uni-osnabrueck.de/universitaet/organisation/familien-service/'"
                       " target='_blank'>Hier geht es zur Website.</a>",
        "title_new": "Studieren mit Familie",
        "description_new": "Alle Informationen rund um das Thema Studieren mit Familie (z.B. Kinderbetreuung, "
                           "Pflege von Angehörigen) findest du hier: "
                           "<a href='https://www.uni-osnabrueck.de/universitaet/organisation/familien-service/'"
                           " target='_blank'>Hier geht es zur Website.</a>"
    },
    {
        "title": "Studieren mit Familie",
        "description": "Alle Informationen rund um das Thema Studieren mit Familie (z.B. Kinderbetreuung, "
                       "Pflege von Angehörigen) findest du hier:"
                       "<a href='https://www.uni-bremen.de/familie/studierende'"
                       " target='_blank'>Hier geht es zur Website.</a>",
        "title_new": "Studieren mit Familie",
        "description_new": "Alle Informationen rund um das Thema Studieren mit Familie (z.B. Kinderbetreuung, "
                           "Pflege von Angehörigen) findest du hier: "
                           "<a href='https://www.uni-bremen.de/familie/studierende'"
                           " target='_blank'>Hier geht es zur Website.</a>"
    },
    {
        "title": "Studieren mit Familie",
        "description": "Alle Informationen rund um das Thema Studieren mit Familie (z.B. Kinderbetreuung, "
                       "Pflege von Angehörigen) findest du hier:"
                       "<a href='https://www.chancenvielfalt.uni-hannover.de/"
                       "de/angebote/angebote-fuer-familien/'"
                       " target='_blank'>Hier geht es zur Website.</a>",
        "title_new": "Studieren mit Familie",
        "description_new": "Alle Informationen rund um das Thema Studieren mit Familie (z.B. Kinderbetreuung, "
                           "Pflege von Angehörigen) findest du hier: "
                           "<a href='https://www.chancenvielfalt.uni-hannover.de/"
                           "de/angebote/angebote-fuer-familien/'"
                           " target='_blank'>Hier geht es zur Website.</a>"
    },
    {
        "title": "Allgemeiner Studierendenausschuss (AStA)",
        "description": "Allgemeiner Studierendenausschuss (AStA)"
                       " ist die universitätsweite Interessenvertretung der Studierenden und informiert euch"
                       " über Themen wie Bafög, Semesterticket etc."
                       "<a href='https://www.asta.uni-osnabrueck.de/' "
                       "target='_blank'>Hier geht es zur Website.</a>",
        "title_new": "Allgemeiner Studierendenausschuss (AStA)",
        "description_new": "Allgemeiner Studierendenausschuss (AStA)"
                           " ist die universitätsweite Interessenvertretung der Studierenden und informiert euch"
                           " über Themen wie Bafög, Semesterticket etc. "
                           "<a href='https://www.asta.uni-osnabrueck.de/' "
                           "target='_blank'>Hier geht es zur Website.</a>"
    },
    {
        "title": "Allgemeiner Studierendenausschuss (AStA)",
        "description": "Allgemeiner Studierendenausschuss (AStA)"
                       " ist die universitätsweite Interessenvertretung der Studierenden und informiert euch"
                       " über Themen wie Bafög, Semesterticket etc."
                       "<a href='https://www.asta.uni-bremen.de/' "
                       "target='_blank'>Hier geht es zur Website.</a>",
        "title_new": "Allgemeiner Studierendenausschuss (AStA)",
        "description_new": "Allgemeiner Studierendenausschuss (AStA)"
                           " ist die universitätsweite Interessenvertretung der Studierenden und informiert euch"
                           " über Themen wie Bafög, Semesterticket etc. "
                           "<a href='https://www.asta.uni-bremen.de/' "
                           "target='_blank'>Hier geht es zur Website.</a>"
    },
    {
        "title": "Allgemeiner Studierendenausschuss (AStA)",
        "description": "Allgemeiner Studierendenausschuss (AStA)"
                       " ist die universitätsweite Interessenvertretung der Studierenden und informiert euch"
                       " über Themen wie Bafög, Semesterticket etc."
                       "<a href='https://www.asta-hannover.de/' "
                       "target='_blank'>Hier geht es zur Website.</a>",
        "title_new": "Allgemeiner Studierendenausschuss (AStA)",
        "description_new": "Allgemeiner Studierendenausschuss (AStA)"
                           " ist die universitätsweite Interessenvertretung der Studierenden und informiert euch"
                           " über Themen wie Bafög, Semesterticket etc. "
                           "<a href='https://www.asta-hannover.de/' "
                           "target='_blank'>Hier geht es zur Website.</a>"
    },
    {
        "title": "Mensa",
        "description": "Das Studentenwerk bietet dir in seinen Mensen ein vielfältiges Essensangebot."
                       "<a href='https://www.studentenwerk-osnabrueck.de/de/essen/speiseplaene.html' "
                       "target='_blank'>Hier geht es zur Website.</a>",
        "title_new": "Mensa",
        "description_new": "Das Studentenwerk bietet dir in seinen Mensen ein vielfältiges Essensangebot. "
                           "<a href='https://www.studentenwerk-osnabrueck.de/de/essen/speiseplaene.html' "
                           "target='_blank'>Hier geht es zur Website.</a>"
    },
    {
        "title": "Mensa",
        "description": "Das Studentenwerk bietet dir in seinen Mensen ein vielfältiges Essensangebot."
                       "<a href='https://www.stw-bremen.de/de/mensa/uni-mensa' "
                       "target='_blank'>Hier geht es zur Website.</a>",
        "title_new": "Mensa",
        "description_new": "Das Studentenwerk bietet dir in seinen Mensen ein vielfältiges Essensangebot. "
                           "<a href='https://www.stw-bremen.de/de/mensa/uni-mensa' "
                           "target='_blank'>Hier geht es zur Website.</a>"
    },
    {
        "title": "Mensa",
        "description": "Das Studentenwerk bietet dir in seinen Mensen ein vielfältiges Essensangebot."
                       "<a href='https://www.studentenwerk-hannover.de/essen/speiseplaene/alle-mensen-heute/' "
                       "target='_blank'>Hier geht es zur Website.</a>",
        "title_new": "Mensa",
        "description_new": "Das Studentenwerk bietet dir in seinen Mensen ein vielfältiges Essensangebot. "
                           "<a href='https://www.studentenwerk-hannover.de/essen/speiseplaene/alle-mensen-heute/' "
                           "target='_blank'>Hier geht es zur Website.</a>"
    },
    {
        "title": "Wohnungsangebote",
        "description": "Guten und preiswerten Wohnraum zu finden ist nicht immer leicht. Hier findest du "
                       "Informationen und Hilfestellungen:"
                       "<a href='https://www.studentenwerk-osnabrueck.de/de/wohnen.html' "
                       "target='_blank'>Hier geht es zur Website.</a>",
        "title_new": "Wohnungsangebote",
        "description_new": "Guten und preiswerten Wohnraum zu finden ist nicht immer leicht. Hier findest du "
                           "Informationen und Hilfestellungen: "
                           "<a href='https://www.studentenwerk-osnabrueck.de/de/wohnen.html' "
                           "target='_blank'>Hier geht es zur Website.</a>"
    },
    {
        "title": "Wohnungsangebote",
        "description": "Guten und preiswerten Wohnraum zu finden ist nicht immer leicht. Hier findest du "
                       "Informationen und Hilfestellungen:"
                       "<a href='https://www.uni-bremen.de/universitaet/campus/wohnen' "
                       "target='_blank'>Hier geht es zur Website.</a>",
        "title_new": "Wohnungsangebote",
        "description_new": "Guten und preiswerten Wohnraum zu finden ist nicht immer leicht. Hier findest du "
                           "Informationen und Hilfestellungen: "
                           "<a href='https://www.uni-bremen.de/universitaet/campus/wohnen' "
                           "target='_blank'>Hier geht es zur Website.</a>"
    },
    {
        "title": "Wohnungsangebote",
        "description": "Guten und preiswerten Wohnraum zu finden ist nicht immer leicht. Hier findest du "
                       "Informationen und Hilfestellungen:"
                       "<a href='https://www.uni-hannover.de/de/universitaet/campus-und-stadt/wohnen/' "
                       "target='_blank'>Hier geht es zur Website.</a>",
        "title_new": "Wohnungsangebote",
        "description_new": "Guten und preiswerten Wohnraum zu finden ist nicht immer leicht. Hier findest du "
                           "Informationen und Hilfestellungen: "
                           "<a href='https://www.uni-hannover.de/de/universitaet/campus-und-stadt/wohnen/' "
                           "target='_blank'>Hier geht es zur Website.</a>"
    },
    {
        "title": "Zentrales Prüfungsamt",
        "description": "Das zentrale Prüfungsamt ist zuständig bei Fragen und Problemen rund um "
                       "Prüfungsangelegenheiten."
                       "<a href='https://www.uni-hannover.de/de/universitaet/"
                       "organisation/dezernate/dezernat-6/pruefungsamt/'"
                       "target='_blank'>Hier geht es zur Website.</a>",
        "title_new": "Zentrales Prüfungsamt",
        "description_new": "Das zentrale Prüfungsamt ist zuständig bei Fragen und Problemen rund um "
                           "Prüfungsangelegenheiten. "
                           "<a href='https://www.uni-hannover.de/de/universitaet/"
                           "organisation/dezernate/dezernat-6/pruefungsamt/'"
                           "target='_blank'>Hier geht es zur Website.</a>"
    },
    {
        "title": "Mehr-Fächer-Prüfungsamt PATMOS",
        "description": "Das Mehrfächer-Prüfungsamt ist zuständig für die Prüfungsadministration des "
                       "fachübergreifenden Bereichs (Kerncurriculum Lehrerbildung"
                       ", allgemeine Schlüsselkompetenzen) "
                       "und für die Erstellung von übergreifenden Bescheinigungen, Leistungsübersichten sowie "
                       "Abschlusszeugnissen in den Mehrfächer-Studiengängen."
                       "<a href='https://www.uni-osnabrueck.de/universitaet/organisation/zentrale-verwaltung/"
                       "studentische-angelegenheiten/mehrfaecher-pruefungsamt-patmos/' "
                       "target='_blank'>Hier geht es zur Website.</a>",
        "title_new": "Mehr-Fächer-Prüfungsamt PATMOS",
        "description_new": "Das Mehrfächer-Prüfungsamt ist zuständig für die Prüfungsadministration des "
                           "fachübergreifenden Bereichs (Kerncurriculum Lehrerbildung"
                           ", allgemeine Schlüsselkompetenzen) "
                           "und für die Erstellung von übergreifenden Bescheinigungen, Leistungsübersichten sowie "
                           "Abschlusszeugnissen in den Mehrfächer-Studiengängen. "
                           "<a href='https://www.uni-osnabrueck.de/universitaet/organisation/zentrale-verwaltung/"
                           "studentische-angelegenheiten/mehrfaecher-pruefungsamt-patmos/' "
                           "target='_blank'>Hier geht es zur Website.</a>"
    },
]

question_changeset = [
    {
        "question_text": "Hier kannst du eine E-Mail Adresse hinterlegen um einmal wöchentlich an die Planung deines "
                         "Auslandsaufenthaltes erinnert zu werden.",
        "question_text_new": "Hier kannst du eine E-Mail-Adresse hinterlegen um einmal wöchentlich an die Planung deines "
                             "Auslandsaufenthaltes erinnert zu werden."
    },
    {
        "question_text": 'Möchtest du E-mail Benachrichtigungen erhalten,'
                         ' wenn ich neue Resourcen basierend auf deiner Belegungshistorie gefunden habe? <br> '
                         'WARNUNG: Wenn du deine E-mail Adresse angibst,'
                         ' bist du für SIDDATA nicht mehr annonym!<br>'
                         'Du kannst deine E-mail Adresse jederzeit wieder löschen.',
        "question_text_new": 'Möchtest du E-mail Benachrichtigungen erhalten,'
                             ' wenn ich neue Resourcen basierend auf deiner Belegungshistorie gefunden habe? <br> '
                             'WARNUNG: Wenn du deine E-mail Adresse angibst,'
                             ' bist du für Siddata nicht mehr annonym!<br>'
                             'Du kannst deine E-mail Adresse jederzeit wieder löschen.'
    },
    {
        "question_text": "Ich bearbeite Texte oder Aufgaben zusammen mit meinen Studienkolleg*innen.",
        "question_text_new": "Ich bearbeite Texte oder Aufgaben zusammen mit meinen Mitstudierenden."
    },
    {
        "question_text": "Ich nehme mir Zeit, um mit Studienkolleg*innen über den Stoff zu diskutieren.",
        "question_text_new": "Ich nehme mir Zeit, um mit Mitstudierenden über den Stoff zu diskutieren."
    },
    {
        "question_text": 'Gebe hier ein einzelnes deiner fachliches Interessen (z.B. "Chemie") ein',
        "question_text_new": 'Hier kannst du eines deiner fachlichen Interessen eingeben (z.B. „Chemie“)'
    },
    {
        "question_text": 'Möchtest du E-mail Benachrichtigungen erhalten,'
                         ' wenn ich neue Resourcen zu deinem Interesse gefunden habe? <br> '
                         'WARNUNG: Wenn du deine E-mail Adresse angibst,'
                         ' bist du für SIDDATA nicht mehr annonym!<br>'
                         'Du kannst deine E-mail Adresse jederzeit wieder löschen.',
        "question_text_new": 'Möchtest du E-mail Benachrichtigungen erhalten,'
                             ' wenn ich neue Resourcen zu deinem Interesse gefunden habe? <br> '
                             'WARNUNG: Wenn du deine E-mail Adresse angibst,'
                             ' bist du für Siddata nicht mehr annonym!<br>'
                             'Du kannst deine E-mail Adresse jederzeit wieder löschen.'
    },
    {
        "question_text": "Wenn Du Probleme hast, Deine fachlichen Interessen zu formulieren,"
                         " hilft Dir eine kleine Übung. Hier kannst du dir folgende Fragen beantworten:<br>"
                         "<ul>"
                         " <li>Wenn Du an die letzten Klausuren denkst,"
                         " bei welchen Themen fiel Dir das Lernen besonders leicht?</li>"
                         " <li>Wenn Du an Deine letzten Veranstaltungen denkst,"
                         " welche Themen haben Dich besonders interessiert?</li>"
                         " <li>Welches Buch hast Du Dir ausgeliehen ohne dass"
                         " es auf einer Leseliste stand?</li>"
                         " <li>Was hast Du Deinen"
                         " Freunden von Deinem Studium inhaltlich erzählt?</li>"
                         " <li>Über welches Thema hast Du noch nachgedacht,"
                         " obwohl Du schon längst etwas anderes gemacht hast?</li>"
                         "</ul>",
        "question_text_new": "WennduProbleme hast,deine fachlichen Interessen zu formulieren,"
                             " hilftdireine kleine Übung. Hier kannst du dir folgende Fragen beantworten:<br>"
                             "<ul>"
                             " <li>Wenn du an die letzten Klausuren denkst,"
                             " bei welchen Themen fieldirdas Lernen besonders leicht?</li>"
                             " <li>Wenn du andeine letzten Veranstaltungen denkst,"
                             " welche Themen haben Dich besonders interessiert?</li>"
                             " <li>Welches Buch hastduDir ausgeliehen ohne dass"
                             " es auf einer Leseliste stand?</li>"
                             " <li>Was hast du deinen"
                             " Freunden von Deinem Studium inhaltlich erzählt?</li>"
                             " <li>Über welches Thema hastdunoch nachgedacht,"
                             " obwohlduschon längst etwas anderes gemacht hast?</li>"
                             "</ul>"
    },
]

goal_changeset = [
    {
        "title": 'Empfehlungen basierend auf Belegungen ähnlicher Nutzer*innen',
        "title_new": 'Empfehlungen basierend auf Belegungen ähnlicher Nutzenden',
    },
    {
        "description": "Hier kannst Du durch die Beantwortung einer Reihe von Fragen dein Langzeitgedächtnis, "
                       "dein Kurzzeitgedächnis und deine Multitaskingfähigkeit einschätzen.",
        "description_new": "Hier kannst du durch die Beantwortung einer Reihe von Fragen dein Langzeitgedächtnis, "
                           "dein Kurzzeitgedächnis und deine Multitaskingfähigkeit einschätzen.",
    },
    {
        "description": "Hier kannst Du über die Teilnahme an eine Online-Experiment dein Langzeitgedächtnis, "
                       "dein Kurzzeitgedächnis und deine Multitaskingfähigkeit einschätzen.",
        "description_new": "Hier kannstduüber die Teilnahme an eine Online-Experiment dein Langzeitgedächtnis, "
                           "dein Kurzzeitgedächnis und deine Multitaskingfähigkeit einschätzen.",
    },
    {
        "description": "Hier kannst Du durch die Beantwortung einer Reihe von Fragen dein Langzeitgedächtnis, "
                       "dein Kurzzeitgedächnis und deine Multitaskingfähigkeit einschätzen.",
        "description_new": "Hier kannstdudurch die Beantwortung einer Reihe von Fragen dein Langzeitgedächtnis, "
                           "dein Kurzzeitgedächnis und deine Multitaskingfähigkeit einschätzen."
    },
    {
        "description": "Hier kannst Du über die Teilnahme an eine Online-Experiment dein Langzeitgedächtnis, "
                       "dein Kurzzeitgedächnis und deine Multitaskingfähigkeit einschätzen.",
        "description_new": "Hier kannstduüber die Teilnahme an eine Online-Experiment dein Langzeitgedächtnis, "
                           "dein Kurzzeitgedächnis und deine Multitaskingfähigkeit einschätzen."
    },
]


def migrate_wording(apps, schema_editor):
    Activity = apps.get_model("backend", "Activity")
    Question = apps.get_model("backend", "Question")
    Goal = apps.get_model("backend", "Goal")

    for change in activity_changeset:
        if 'title' in change.keys() and 'description' in change.keys():
            aq = Activity.objects.filter(title=change['title'], description=change['description'])
            for a in aq:
                a.title = change['title_new']
                a.description = change['description_new']
                a.save()
        elif 'title' in change.keys() and 'description' not in change.keys():
            aq = Activity.objects.filter(title=change['title'])
            for a in aq:
                a.title = change['title_new']
                a.save()
        elif 'title' not in change.keys() and 'description' in change.keys():
            aq = Activity.objects.filter(description=change['description'])
            for a in aq:
                a.description = change['description_new']
                a.save()

    for change in question_changeset:
        qq = Question.objects.filter(question_text=change['question_text'])
        for q in qq:
            q.question_text = change['question_text_new']
            q.save()

    for change in goal_changeset:
        if 'title' in change.keys() and 'description' in change.keys():
            gq = Goal.objects.filter(title=change['title'], description=change['description'])
            for g in gq:
                g.title = change['title_new']
                g.description = change['description_new']
                g.save()
        elif 'title' in change.keys() and 'description' not in change.keys():
            gq = Goal.objects.filter(title=change['title'])
            for g in gq:
                gq.title = change['title_new']
                gq.save()
        elif 'title' not in change.keys() and 'description' in change.keys():
            gq = Goal.objects.filter(description=change['description'])
            for g in gq:
                g.description = change['description_new']
                g.save()


def undo_migrate_wording(apps, schema_editor):
    Activity = apps.get_model("backend", "Activity")
    Question = apps.get_model("backend", "Question")
    Goal = apps.get_model("backend", "Goal")

    for change in activity_changeset:
        if 'title' in change.keys() and 'description' in change.keys():
            aq = Activity.objects.filter(title=change['title_new'], description=change['description_new'])
            for a in aq:
                a.title = change['title']
                a.description = change['description']
                a.save()
        elif 'title' in change.keys() and 'description' not in change.keys():
            aq = Activity.objects.filter(title=change['title_new'])
            for a in aq:
                a.title = change['title']
                a.save()
        elif 'title' not in change.keys() and 'description' in change.keys():
            aq = Activity.objects.filter(description=change['description_new'])
            for a in aq:
                a.description = change['description']
                a.save()

    for change in question_changeset:
        qq = Question.objects.filter(question_text=change['question_text_new'])
        for q in qq:
            q.question_text = change['question_text']
            q.save()

    for change in goal_changeset:
        if 'title' in change.keys() and 'description' in change.keys():
            gq = Goal.objects.filter(title=change['title_new'], description=change['description_new'])
            for g in gq:
                g.title = change['title']
                g.description = change['description']
                g.save()
        elif 'title' in change.keys() and 'description' not in change.keys():
            gq = Goal.objects.filter(title=change['title_new'])
            for g in gq:
                gq.title = change['title']
                gq.save()
        elif 'title' not in change.keys() and 'description' in change.keys():
            gq = Goal.objects.filter(description=change['description_new'])
            for g in gq:
                g.description = change['description']
                g.save()


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20211220_1036'),
    ]

    operations = [
        migrations.RunPython(migrate_wording, reverse_code=undo_migrate_wording),
    ]
