# Generated by Django 3.1.2 on 2022-01-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_wording_p3'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
